  <section class="panel home-map-panel" x-data="{ reportType: 'all', timeFrame: '1', updateMap() { this.$dispatch('operational-map-filter', { reportType: this.reportType, timeFrame: this.timeFrame }); } }">
    <div class="panel-title">Class Map</div>
    <div class="panel-body">
      <div class="home-map-canvas">
        <div id="homeLeafletMap" class="home-leaflet-map" aria-label="Class location map"></div>
        <div class="map-filter home-map-filter">
          <select id="homeReportType" aria-label="Class status" x-model="reportType" x-on:change="updateMap()"><option value="all" data-label="All">All Classes</option><option value="ongoing" data-label="Ongoing">Ongoing Classes</option><option value="upcoming" data-label="Upcoming">Upcoming Classes</option><option value="past" data-label="Past">Past Classes</option></select>
          <span>Time Frame:</span>
          <select id="homeTimeFrame" aria-label="Time frame" x-model="timeFrame" x-on:change="updateMap()"><option value="1">Next 1 Week</option><option value="2">Next 2 Weeks</option><option value="3">Next 3 Weeks</option><option value="4">Next 1 Month</option><option value="8">Next 2 Months</option><option value="12">Next 3 Months</option><option value="26">Next 6 Months</option><option value="52">Next Year</option><option value="all">All Time</option></select>
        </div>
      </div>
    </div>
</section>
@push('scripts')
<script>
  window.wellsharpClassPoints = @json($mapPoints);
  window.wellsharpClassModalData = @json($classModalData);
</script>
@endpush

  @include('operational._class-table', ['title' => 'Ongoing Classes', 'classes' => $ongoingClasses, 'roleLabel' => $roleLabel, 'emptyMessage' => 'No ongoing Classes are available right now.', 'emptyHint' => 'Ongoing means the Class is Active. Any eligible Proctor or Instructor can control it.', 'compact' => false])
  @include('operational._class-table', ['title' => 'Upcoming Classes', 'classes' => $upcomingClasses, 'roleLabel' => $roleLabel, 'emptyMessage' => 'No upcoming Classes are available right now.', 'emptyHint' => 'Upcoming means the Class is Planned and has not started yet.', 'compact' => true])
  @include('operational._class-table', ['title' => 'Past Classes', 'classes' => $pastClasses, 'roleLabel' => $roleLabel, 'emptyMessage' => 'No past Classes are available right now.', 'emptyHint' => 'Past includes Classes marked Completed or Cancelled.', 'past' => true])

  <section class="panel data-panel compact-panel client-questions">
    <div class="panel-title">Client Questions</div>
    <div class="data-panel-body">
      <ul>
        <li>Confirm Release behavior in Scores &amp; Reports: it appears to close/finalize the selected trainee exam at its current state.</li>
        <li>Confirm proctor certificate PDF source: should it be uploaded while adding a proctor, or generated by the system?</li>
        <li>Clarify Browse Classes Retakes meaning and how the retake count should be calculated/displayed.</li>
        <li>Clarify Proctor column survey labels: why some rows show Survey Complete or Survey Incomplete and others do not.</li>
      </ul>
    </div>
  </section>
