@extends('layouts.operational')

@section('operational-content')
@php($operationalPrefix = auth()->user()->hasRole('proctor') ? 'proctor' : 'instructor')
<style>.attempt-report-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.attempt-report-head h1{margin:0 0 6px}.attempt-report-actions{display:flex;gap:8px;flex-wrap:wrap}.attempt-summary-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.attempt-summary-grid>div{padding:14px;background:#f5f8fa;border:1px solid #d8e1e7}.attempt-summary-grid strong,.attempt-summary-grid span{display:block}.attempt-summary-grid strong{font-size:20px;margin-top:5px}.question-report-table{width:100%;border-collapse:collapse}.question-report-table th,.question-report-table td{padding:12px;border-bottom:1px solid #d8e1e7;text-align:left;vertical-align:top}.question-report-table th{font-size:11px;text-transform:uppercase;color:#71808d}.question-state{font-weight:600}.question-state.correct{color:#067647}.question-state.incorrect{color:#b42318}.question-state.unanswered{color:#71808d}.report-result{font-weight:700}.report-result.passed{color:#067647}.report-result.failed{color:#b42318}.report-result.pending{color:#71808d}.report-image{display:block;max-width:180px;max-height:110px;margin-top:8px;border:1px solid #d8e1e7;border-radius:5px;object-fit:contain;background:#fff}@media(max-width:900px){.attempt-summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.attempt-report-head{flex-direction:column}}@media(max-width:600px){.attempt-summary-grid{grid-template-columns:1fr}}</style>
<div class="attempt-report-head"><div><span class="overview-tab">Scores &amp; Reports</span><h1>{{ $attempt->student?->display_name ?: $attempt->student?->wellsharp_id }}</h1><p>{{ $attempt->exam?->name ?: 'Assessment' }} · Attempt {{ $attempt->attempt_number }}</p></div><div class="attempt-report-actions"><a class="blue-btn" href="{{ route($operationalPrefix.'.analytics.results') }}">Back to reports</a>@if(!$attempt->released_at)<form method="POST" action="{{ route($operationalPrefix.'.analytics.attempts.release', $attempt) }}" onsubmit="return confirm('Release this trainee exam in its current state? Unanswered questions will be scored incorrect.');">@csrf<button class="tiny-green" type="submit">Release exam</button></form>@endif</div></div>

<section class="panel"><div class="panel-title">Attempt summary</div><div class="panel-body"><div class="attempt-summary-grid"><div><span>Score</span><strong>{{ $attempt->score !== null ? number_format((float) $attempt->score, 2).'%' : 'Pending' }}</strong></div><div><span>Result</span><strong class="report-result {{ $attempt->passed === true ? 'passed' : ($attempt->passed === false ? 'failed' : 'pending') }}">{{ $attempt->passed === true ? 'Passed' : ($attempt->passed === false ? 'Failed' : 'Pending') }}</strong></div><div><span>Attempt state</span><strong>{{ $attempt->status->label() }}</strong></div><div><span>Started</span><strong>{{ $attempt->started_at?->format('Y-m-d H:i') ?: 'Not set' }}</strong></div><div><span>Released</span><strong>{{ $attempt->released_at?->format('Y-m-d H:i') ?: 'Not released' }}</strong></div></div></div></section>

<section class="panel"><div class="panel-title">Trainee and Class</div><div class="panel-body"><div class="form-grid"><div><span class="muted">WellSharp ID</span><p>{{ $attempt->student?->wellsharp_id }}</p></div><div><span class="muted">Email</span><p>{{ $attempt->student?->email ?: 'Not set' }}</p></div><div><span class="muted">Subject</span><p>{{ $attempt->exam?->subject?->name ?: 'Not assigned' }}</p></div><div><span class="muted">Class</span><p>{{ $attempt->schedule?->trainingClass?->class_number ?: 'Not assigned' }}</p></div><div><span class="muted">Provider</span><p>{{ $attempt->schedule?->provider?->name ?: $attempt->schedule?->trainingClass?->provider?->name ?: 'Not assigned' }}</p></div><div><span class="muted">Passing score</span><p>{{ $attempt->exam?->passing_score !== null ? $attempt->exam->passing_score.'%' : 'Not configured' }}</p></div></div></div></section>

<section class="panel"><div class="panel-title">Question scoring</div><div class="panel-body"><div class="report-table-wrap"><table class="question-report-table"><thead><tr><th>#</th><th>Question</th><th>Trainee answer</th><th>Correct answer</th><th>Points</th><th>Result</th></tr></thead><tbody>@forelse($breakdown as $question)<tr><td>{{ $question['display_order'] }}</td><td>{{ $question['question_text'] }}@if($question['question_image_url'])<img class="report-image" src="{{ $question['question_image_url'] }}" alt="Question image">@endif</td><td>{{ $question['answer'] ?: 'Unanswered' }}@if($question['answer_image_url'])<img class="report-image" src="{{ $question['answer_image_url'] }}" alt="Trainee answer image">@endif</td><td>{{ $question['correct_answer'] ?: 'Not configured' }}@if($question['correct_answer_image_url'])<img class="report-image" src="{{ $question['correct_answer_image_url'] }}" alt="Correct answer image">@endif</td><td>{{ number_format((float) $question['earned_points'], 2) }} / {{ number_format((float) $question['points'], 2) }}</td><td class="question-state {{ $question['is_correct'] ? 'correct' : ($question['answered'] ? 'incorrect' : 'unanswered') }}">{{ $question['is_correct'] ? 'Correct' : ($question['answered'] ? 'Incorrect' : 'Unanswered') }}</td></tr>@empty<tr><td colspan="6">Question scoring will be available after the attempt is submitted or released.</td></tr>@endforelse</tbody></table></div></div></section>
@endsection
