@extends('layouts.admin')
@section('admin-content')
<div class="page-head hero"><div><span class="admin-kicker">{{ $group->code ?: 'Group' }}</span><h1>{{ $group->name }}</h1><p>{{ $group->students->count() }} active Students · {{ $group->exam_schedules_count }} exam schedules</p></div><div class="admin-page-actions"><a class="btn secondary" href="{{ route('admin.groups.edit', $group) }}">Edit</a>@if($group->status->value === 'active')<form method="POST" action="{{ route('admin.groups.archive', $group) }}">@csrf @method('PATCH')<button class="btn danger">Archive</button></form>@else<form method="POST" action="{{ route('admin.groups.unarchive', $group) }}">@csrf @method('PATCH')<button class="btn secondary">Unarchive</button></form>@endif</div></div>
<div class="admin-bento">
<div class="admin-bento-card admin-bento-card--wide"><div class="admin-card-head"><span class="admin-card-icon cool">🎓</span><h3>Students</h3></div><div class="table-wrap"><table class="table"><thead><tr><th>WellSharp ID</th><th>Name</th><th>Age</th><th></th></tr></thead><tbody>@forelse($students as $student)<tr><td>{{ $student->wellsharp_id }}</td><td>{{ $student->display_name }}</td><td>{{ $student->profile?->age ?: '—' }}</td><td><form method="POST" action="{{ route('admin.groups.members.destroy', [$group, $student]) }}">@csrf @method('DELETE')<button class="link-button" type="submit">Remove</button></form></td></tr>@empty<tr><td colspan="4"><div class="admin-empty-row"><span class="admin-empty-row-icon">🎓</span>No active Students.</div></td></tr>@endforelse</tbody></table></div></div>
<div class="admin-bento-card admin-bento-card--wide" x-data="{ search: '', selected: [] }"><div class="admin-card-head"><span class="admin-card-icon">➕</span><h3>Add Students<span class="required-mark" aria-hidden="true">*</span></h3><span class="badge active" style="margin-left:auto" x-text="selected.length + ' selected'"></span></div><p class="admin-card-note">Search by name or WellSharp ID, then select one or more Students.</p><div class="search"><input x-model="search" type="search" placeholder="Start typing a student name or WellSharp ID" autocomplete="off" autofocus><span class="muted" x-text="search ? 'Filtering results…' : 'All available Students'"></span></div><form method="POST" action="{{ route('admin.groups.members.store', $group) }}">@csrf<div class="check-grid">@forelse($availableStudents as $student)<label class="student-select-option" data-student-option data-search="{{ strtolower($student->display_name.' '.$student->wellsharp_id) }}" x-show="!search || $el.dataset.search.includes(search.toLowerCase())" x-cloak><input class="student-checkbox" x-model="selected" type="checkbox" name="student_ids[]" value="{{ $student->id }}"> <span><strong>{{ $student->display_name }}</strong><br><small class="muted">{{ $student->wellsharp_id }}</small></span></label>@empty<p class="muted">All Students are already members.</p>@endforelse</div><p class="muted" x-show="search && !Array.from($root.querySelectorAll('[data-student-option]')).some(option => option.dataset.search.includes(search.toLowerCase()))" x-cloak>No matching Students found.</p>@if($availableStudents->isNotEmpty())<button class="btn" style="margin-top:18px" type="submit" x-bind:disabled="selected.length === 0">Add selected Students</button>@endif</form></div>
</div>
<style>[x-cloak]{display:none!important}.link-button{border:0;background:none;padding:0;color:var(--admin-blue);font:inherit;cursor:pointer}.link-button:hover{text-decoration:underline}.student-select-option{display:flex;align-items:flex-start;gap:8px}.student-select-option input{margin-top:4px}</style>
@endsection
