@php
    $selected = old('question_ids', $exam->examQuestions?->pluck('question_id')->all() ?: []);
    $orders = old('display_orders', $exam->examQuestions?->pluck('display_order', 'question_id')->all() ?: []);
    $currentSubject = old('course_id', $selectedCourseId ?? $course?->id);
@endphp
<div class="form-grid">
    <div class="field full"><label for="course_id">Subject</label><select id="course_id" name="course_id" required><option value="">Select a Subject</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected((string) $currentSubject === (string) $subject->id)>{{ $subject->name }} ({{ $subject->code }})</option>@endforeach</select><small class="muted">The Subject owns the reusable question bank for this exam.</small></div>
    <div class="field"><label for="name">Exam name</label><input id="name" name="name" value="{{ old('name', $exam->name) }}" required></div>
    <div class="field"><label for="code">Exam code</label><input id="code" name="code" value="{{ old('code', $exam->code) }}"></div>
    <div class="field"><label for="question_order_mode">Question order</label><select id="question_order_mode" name="question_order_mode" required>@foreach(['static' => 'Static', 'shuffle' => 'Shuffle'] as $value => $label)<option value="{{ $value }}" @selected(old('question_order_mode', $exam->question_order_mode?->value) === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label for="status">Status</label><select id="status" name="status" required>@foreach(['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $exam->status?->value) === $value)>{{ $label }}</option>@endforeach</select></div>
    <div class="field"><label for="passing_score">Passing Score (%)</label><input id="passing_score" type="number" name="passing_score" min="0" max="100" value="{{ old('passing_score', $exam->passing_score) }}"><small class="muted">The score required to pass.</small></div>
    <div class="field"><label for="retake_score">Retake Score (%)</label><input id="retake_score" type="number" name="retake_score" min="0" max="100" value="{{ old('retake_score', $exam->retake_score) }}"><small class="muted">The minimum score used for retake reporting.</small></div>
    <div class="field full"><label for="description">Description</label><textarea id="description" name="description">{{ old('description', $exam->description) }}</textarea></div>
</div>
<div class="field full" style="margin-top:22px"><label>Questions</label><p class="muted">Select questions from the chosen Subject. Scheduling is completed separately after the exam is saved.</p><div class="table-wrap"><table class="table"><thead><tr><th>Select</th><th>Order</th><th>Question</th><th>Subject</th><th>Type</th><th>Difficulty</th></tr></thead><tbody>@forelse($questions as $question)<tr><td><input type="checkbox" name="question_ids[]" value="{{ $question->id }}" @checked(in_array($question->id, $selected))></td><td><input style="width:80px" type="number" name="display_orders[{{ $question->id }}]" value="{{ $orders[$question->id] ?? $loop->iteration }}" min="1"></td><td><div class="admin-question-cell">@if($question->question_image_path)<img class="admin-question-thumb" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($question->question_image_path) }}" alt="Question image">@endif<div><span>{{ $question->question_text }}</span>@if($question->options->whereNotNull('image_path')->isNotEmpty() || $question->correct_answer_image_path)<small class="image-count">{{ $question->options->whereNotNull('image_path')->count() + ($question->correct_answer_image_path ? 1 : 0) }} answer image{{ $question->options->whereNotNull('image_path')->count() + ($question->correct_answer_image_path ? 1 : 0) === 1 ? '' : 's' }}</small>@endif</div></div></td><td>{{ $question->course?->name }}</td><td>{{ $question->type->label() }}</td><td>{{ $question->difficulty->label() }}</td></tr>@empty<tr><td colspan="6" class="muted">Choose a Subject with active questions first.</td></tr>@endforelse</tbody></table></div></div>
<div class="actions" style="margin-top:20px"><button class="btn">Save exam</button><a class="btn secondary" href="{{ $exam->exists ? route('admin.exams.show', $exam) : route('admin.exams.index') }}">Cancel</a></div>
