@extends('layouts.admin')
@section('admin-content')
<div class="page-head hero"><div><span class="admin-kicker">{{ $course->name }}</span><h1>{{ $exam->name }}</h1><p>{{ $exam->question_order_mode->label() }} &middot; {{ $exam->status->label() }}</p></div><div class="admin-page-actions"><a class="btn secondary" href="{{ route('admin.exams.edit', $exam) }}">Edit exam</a><a class="btn" href="{{ route('admin.exam-schedules.create', ['exam_id' => $exam->id]) }}">Add group schedule</a></div></div>
<div class="admin-bento">
@if($exam->question_selection_mode?->value !== 'random')
<div class="admin-bento-card admin-bento-card--wide"><div class="admin-card-head"><span class="admin-card-icon">&#10067;</span><h3>Questions</h3><span class="badge active" style="margin-left:auto">{{ $exam->examQuestions->count() }} selected</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Order</th><th>Question</th><th>Type</th><th>Difficulty</th></tr></thead><tbody>@foreach($exam->examQuestions as $examQuestion)<tr><td>{{ $examQuestion->display_order }}</td><td><div class="admin-question-cell">@if($examQuestion->question->question_image_path)<img class="admin-question-thumb" src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($examQuestion->question->question_image_path) }}" alt="Question image">@endif<div><span>{{ $examQuestion->question->question_text }}</span>@if($examQuestion->question->options->whereNotNull('image_path')->isNotEmpty() || $examQuestion->question->correct_answer_image_path)<small class="image-count">{{ $examQuestion->question->options->whereNotNull('image_path')->count() + ($examQuestion->question->correct_answer_image_path ? 1 : 0) }} answer image{{ $examQuestion->question->options->whereNotNull('image_path')->count() + ($examQuestion->question->correct_answer_image_path ? 1 : 0) === 1 ? '' : 's' }}</small>@endif</div></div></td><td>{{ $examQuestion->question->type->label() }}</td><td>{{ $examQuestion->question->difficulty->label() }}</td></tr>@endforeach</tbody></table></div></div>
@endif
<div class="admin-bento-card admin-bento-card--wide"><div class="admin-card-head"><span class="admin-card-icon cool">&#128467;&#65039;</span><h3>Schedules</h3><a href="{{ route('admin.exam-schedules.index', ['exam_id' => $exam->id]) }}" style="margin-left:auto">View all schedules</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Group</th><th>Start date</th><th>End date</th><th>Duration</th><th>Status</th></tr></thead><tbody>@forelse($exam->schedules as $schedule)<tr><td>{{ $schedule->group?->name ?: '&mdash;' }}</td><td>{{ $schedule->start_date?->format('Y-m-d') ?: '&mdash;' }}</td><td>{{ $schedule->end_date?->format('Y-m-d') ?: '&mdash;' }}</td><td>{{ $schedule->duration_minutes }} min per student</td><td><span class="badge {{ $schedule->status->value }}">{{ $schedule->status->label() }}</span></td></tr>@empty<tr><td colspan="5"><div class="admin-empty-row"><span class="admin-empty-row-icon">&#128467;&#65039;</span>This exam has not been scheduled yet.</div></td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
