@extends('layouts.admin')
@section('admin-content')
<style>[x-cloak]{display:none!important}.admin-table-loading{opacity:.55;pointer-events:none}.admin-sort{border:0;background:transparent;color:inherit;font:inherit;font-weight:600;cursor:pointer;padding:0}.admin-sort:hover{color:var(--admin-blue)}.admin-sort-icon{font-size:11px;margin-left:3px}.admin-table-error{background:#fef3f2;color:#b42318;border-radius:5px;padding:10px 12px;margin-bottom:15px}</style>
<div class="page-head"><div><h1>Users</h1><p>Search, filter, and sort users without leaving this page.</p></div><a class="btn" href="{{ route('admin.users.create') }}">Create user</a></div>
<div class="card" x-data="userTable(@js(route('admin.users.data')), @js($initialUsers), @js($initialMeta))">
    <form class="search" x-on:submit.prevent="load(1)">
        <input x-model="search" x-on:input.debounce.350ms="load(1)" placeholder="Search WellSharp ID, name, or email" autocomplete="off">
        <select x-model="roleId" x-on:change="load(1)"><option value="">All Roles</option>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->name }}</option>@endforeach</select>
        <select x-model="status" x-on:change="load(1)"><option value="">All Statuses</option><option value="active">Active</option><option value="disabled">Disabled</option><option value="archived">Archived</option></select>
        <button class="btn secondary" type="submit">Apply</button><button class="btn secondary" type="button" x-show="hasFilters()" x-on:click="clearFilters()" x-cloak>Clear</button>
    </form>
    <div class="admin-table-error" x-show="error" x-text="error" x-cloak></div>
    <div class="table-wrap" x-bind:class="loading ? 'admin-table-loading' : ''"><table class="table"><thead><tr><th><button class="admin-sort" type="button" x-on:click="sortBy('name')">User <span class="admin-sort-icon" x-text="sortIcon('name')"></span></button></th><th>Contact</th><th><button class="admin-sort" type="button" x-on:click="sortBy('role')">Role <span class="admin-sort-icon" x-text="sortIcon('role')"></span></button></th><th>Profile</th><th><button class="admin-sort" type="button" x-on:click="sortBy('status')">Status <span class="admin-sort-icon" x-text="sortIcon('status')"></span></button></th><th></th></tr></thead><tbody><template x-for="user in rows" :key="user.id"><tr><td><strong x-text="user.display_name"></strong><br><span class="muted" x-text="user.wellsharp_id"></span></td><td><span x-text="user.email"></span><br><small class="muted" x-text="user.phone"></small></td><td><span x-text="user.role"></span><template x-if="user.proctor_id"><br><small class="muted">ID: <span x-text="user.proctor_id"></span></small></template></td><td><span x-text="user.birthday"></span><br><small class="muted" x-text="user.location"></small></td><td><span class="badge" x-bind:class="user.status" x-text="user.status_label"></span></td><td><a x-bind:href="user.view_url">View</a></td></tr></template><tr x-show="!loading && rows.length === 0" x-cloak><td colspan="6" class="muted">No users found.</td></tr></tbody></table></div>
    <div class="actions" style="justify-content:space-between;margin-top:18px"><span class="muted" x-text="meta.total ? 'Showing '+meta.from+' to '+meta.to+' of '+meta.total+' users' : 'No users found'"></span><div class="actions"><button class="btn secondary" type="button" x-on:click="load(meta.current_page - 1)" x-bind:disabled="loading || meta.current_page <= 1">Previous</button><span class="muted" x-text="meta.current_page+' / '+meta.last_page"></span><button class="btn secondary" type="button" x-on:click="load(meta.current_page + 1)" x-bind:disabled="loading || meta.current_page >= meta.last_page">Next</button></div></div>
</div>
<script>
    window.userTable = function (endpoint, initialRows, initialMeta) {
        return { endpoint, rows: initialRows || [], meta: initialMeta || { current_page: 1, last_page: 1, total: 0, from: null, to: null }, search: @js($search), roleId: @js((string) $roleId), status: @js($status), sort: 'created_at', direction: 'desc', loading: false, error: '', request: null,
            hasFilters() { return this.search || this.roleId || this.status; }, clearFilters() { this.search = ''; this.roleId = ''; this.status = ''; this.load(1); }, sortIcon(field) { return this.sort === field ? (this.direction === 'asc' ? '▲' : '▼') : '↕'; }, sortBy(field) { if (this.sort === field) this.direction = this.direction === 'asc' ? 'desc' : 'asc'; else { this.sort = field; this.direction = 'asc'; } this.load(1); },
            async load(page) { page = Math.max(1, page || 1); if (this.request) this.request.abort(); this.request = new AbortController(); const params = new URLSearchParams({ page, sort: this.sort, direction: this.direction }); if (this.search) params.set('search', this.search); if (this.roleId) params.set('role_id', this.roleId); if (this.status) params.set('status', this.status); this.loading = true; this.error = ''; try { const response = await fetch(this.endpoint + '?' + params.toString(), { headers: { Accept: 'application/json' }, signal: this.request.signal }); if (!response.ok) throw new Error('User search failed'); const payload = await response.json(); this.rows = payload.data; this.meta = payload.meta; } catch (error) { if (error.name !== 'AbortError') this.error = 'Users could not be loaded. Try again.'; } finally { this.loading = false; } }
        };
    };
</script>
@endsection
