@php
    $isGlobal = $isGlobal ?? false;
    $isEditing = $question->exists;
    $wizardOptions = $question->options?->map(fn ($option): array => [
        'text' => $option->option_text,
        'correct' => $option->is_correct,
        'imageUrl' => $option->image_path ? \Illuminate\Support\Facades\Storage::disk('public')->url($option->image_path) : null,
    ])->values() ?? collect();
    if ($wizardOptions->isEmpty()) {
        $wizardOptions = collect([['text' => '', 'correct' => false, 'imageUrl' => null], ['text' => '', 'correct' => false, 'imageUrl' => null]]);
    }
    $selectedCorrectOption = $wizardOptions->search(fn (array $option): bool => $option['correct'] === true);
    $questionImageUrl = $question->question_image_path ? \Illuminate\Support\Facades\Storage::disk('public')->url($question->question_image_path) : null;
    $correctAnswerImageUrl = $question->correct_answer_image_path ? \Illuminate\Support\Facades\Storage::disk('public')->url($question->correct_answer_image_path) : null;
@endphp
<style>[x-cloak]{display:none!important}</style>
<div class="question-wizard" x-data="questionWizard(@js([
    'questionText' => old('question_text', $question->question_text),
    'questionType' => old('type', $question->type?->value ?? 'true_false'),
    'subjectId' => old('course_id', $question->course_id ?? $course?->id ?? ''),
    'difficulty' => old('difficulty', $question->difficulty?->value ?? 'medium'),
    'defaultMarks' => old('default_marks', $question->default_marks ?? 1),
    'questionImageUrl' => $questionImageUrl,
    'questionImageName' => '',
    'correctAnswerImageUrl' => $correctAnswerImageUrl,
    'correctAnswerImageName' => '',
    'solutionText' => old('solution_text', $question->solution_text),
    'isActive' => (bool) old('is_active', $question->exists ? $question->is_active : true),
    'options' => old('options', $wizardOptions->pluck('text')->all()),
    'optionImages' => $wizardOptions->pluck('imageUrl')->all(),
    'optionImageNames' => array_fill(0, $wizardOptions->count(), ''),
    'correctOption' => old('correct_option', $selectedCorrectOption === false ? 0 : $selectedCorrectOption),
    'correctAnswer' => old('correct_answer', $question->type?->value === 'true_false' ? ($question->correct_answer_boolean ? 'true' : 'false') : $question->correct_answer_text),
]))">
    <div class="wizard-panel">
        <div class="wizard-tabs" role="tablist"><button class="wizard-tab" type="button" x-bind:class="step === 1 ? 'active' : ''" x-on:click="step = 1">1 Details</button><button class="wizard-tab" type="button" x-bind:class="step === 2 ? 'active' : ''" x-on:click="step = 2">2 Settings</button><button class="wizard-tab" type="button" x-bind:class="step === 3 ? 'active' : ''" x-on:click="step = 3">3 Solution</button></div>
        <div class="wizard-body">
            <section x-show="step === 1" x-cloak>
                <div class="field"><x-admin.label for="wizard_question_type" required>Question type</x-admin.label><select id="wizard_question_type" name="type" x-model="questionType" required><option value="">Select an option</option>@foreach($types as $item)<option value="{{ $item->value }}">{{ $item->label() }}</option>@endforeach</select></div>
                <div class="field"><x-admin.label for="wizard_question_text" required>Question</x-admin.label><div class="wizard-editor"><div class="wizard-toolbar"><button type="button" x-on:click="insertMarker('questionText', 'Bold')"><strong>B</strong></button><button type="button" x-on:click="insertMarker('questionText', 'Italic')"><em>I</em></button><button type="button" x-on:click="insertMarker('questionText', 'Underline')"><u>U</u></button><button type="button" x-on:click="insertMarker('questionText', 'Link')">Link</button><button type="button">H2</button><button type="button">H3</button></div><textarea id="wizard_question_text" x-ref="questionText" name="question_text" x-model="questionText" required></textarea></div></div>
                <div class="field image-field"><x-admin.label for="wizard_question_image">Question image <small>(optional)</small></x-admin.label><div class="upload-box"><label class="upload-dropzone" for="wizard_question_image"><span class="upload-icon" aria-hidden="true">↥</span><span class="upload-copy"><strong x-text="questionImageName || 'Choose an image'">Choose an image</strong><small>Drag and drop or browse from your device</small></span><span class="upload-browse">Browse</span></label><input class="upload-input" id="wizard_question_image" type="file" name="question_image" accept="image/jpeg,image/png,image/gif,image/webp" x-on:change="questionImageName = $event.target.files[0]?.name || ''"></div><small class="wizard-helper">JPG, PNG, GIF, or WebP. The server converts it to WebP.</small><template x-if="questionImageUrl"><div><img class="question-image-preview" x-bind:src="questionImageUrl" alt="Current question image"><label class="image-remove"><input type="checkbox" name="remove_question_image" value="1"> Remove current image</label></div></template></div>
            </section>
            <section x-show="step === 2" x-cloak>
                <div class="wizard-grid"><div class="field wizard-full"><x-admin.label for="wizard_subject" required>Subject</x-admin.label>@if($isGlobal)<select id="wizard_subject" name="course_id" x-model="subjectId" required><option value="">Select an option</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }} ({{ $subject->code }})</option>@endforeach</select>@else<div class="wizard-readonly">{{ $course->name }} ({{ $course->code }})</div>@endif</div><div class="field"><x-admin.label for="wizard_difficulty" required>Difficulty</x-admin.label><select id="wizard_difficulty" name="difficulty" x-model="difficulty" required>@foreach($difficulties as $item)<option value="{{ $item->value }}">{{ $item->label() }}</option>@endforeach</select></div><div class="field"><x-admin.label for="wizard_marks">Default marks</x-admin.label><input id="wizard_marks" name="default_marks" type="number" min="0" step="0.01" x-model="defaultMarks"></div></div>
                <p class="wizard-helper">Exam time is configured in the Exam schedule. Each student receives that many minutes from the moment they start.</p><div class="wizard-switch"><input id="wizard_active" type="hidden" name="is_active" value="0"><input type="checkbox" value="1" x-model="isActive" name="is_active" id="wizard_active_toggle"><label for="wizard_active_toggle" style="margin:0">Active</label></div>
            </section>
            <section x-show="step === 3" x-cloak>
                <div class="field"><x-admin.label for="wizard_solution">Solution</x-admin.label><div class="wizard-editor"><div class="wizard-toolbar"><button type="button" x-on:click="insertMarker('solutionText', 'Bold')"><strong>B</strong></button><button type="button" x-on:click="insertMarker('solutionText', 'Italic')"><em>I</em></button><button type="button">H2</button><button type="button">H3</button></div><textarea id="wizard_solution" x-ref="solutionText" name="solution_text" x-model="solutionText" placeholder="Explain the correct answer or rationale"></textarea></div></div>
                <div class="field" x-show="questionType === 'true_false'"><x-admin.label for="wizard_true_false_answer" required-if="questionType === 'true_false'">Correct answer</x-admin.label><select id="wizard_true_false_answer" name="correct_answer" x-model="correctAnswer" x-bind:disabled="questionType !== 'true_false'"><option value="true">True</option><option value="false">False</option></select></div>
                <div class="field" x-show="questionType === 'input'"><x-admin.label for="wizard_input_answer" required-if="questionType === 'input'">Correct answer</x-admin.label><input id="wizard_input_answer" name="correct_answer" x-model="correctAnswer" x-bind:disabled="questionType !== 'input'" placeholder="Expected text answer"></div>
                <div class="field image-field" x-show="questionType !== 'mcq'"><x-admin.label for="wizard_correct_answer_image">Correct answer image <small>(optional)</small></x-admin.label><div class="upload-box"><label class="upload-dropzone" for="wizard_correct_answer_image"><span class="upload-icon" aria-hidden="true">↥</span><span class="upload-copy"><strong x-text="correctAnswerImageName || 'Choose an image'">Choose an image</strong><small>Drag and drop or browse from your device</small></span><span class="upload-browse">Browse</span></label><input class="upload-input" id="wizard_correct_answer_image" type="file" name="correct_answer_image" accept="image/jpeg,image/png,image/gif,image/webp" x-bind:disabled="questionType === 'mcq'" x-on:change="correctAnswerImageName = $event.target.files[0]?.name || ''"></div><small class="wizard-helper">Use this for an image-based answer on True/False or input questions.</small><template x-if="correctAnswerImageUrl"><div><img class="question-image-preview" x-bind:src="correctAnswerImageUrl" alt="Current answer image"><label class="image-remove"><input type="checkbox" name="remove_correct_answer_image" value="1"> Remove current image</label></div></template></div>
                <div class="field" x-show="questionType === 'mcq'"><x-admin.label required-if="questionType === 'mcq'">Options <small>Choose the correct option.</small></x-admin.label><template x-for="(option, index) in options" :key="index"><div class="wizard-choice"><div class="option-content"><input class="choice-text" name="options[]" x-model="options[index]" x-bind:placeholder="'Option ' + String.fromCharCode(65 + index)" x-bind:disabled="questionType !== 'mcq'" required><div class="upload-box upload-box-compact"><label class="upload-dropzone" x-bind:for="'option_image_' + index"><span class="upload-icon" aria-hidden="true">↥</span><span class="upload-copy"><strong x-text="optionImageNames[index] || 'Add answer image'">Add answer image</strong><small>Optional image</small></span><span class="upload-browse">Browse</span></label><input class="upload-input" x-bind:id="'option_image_' + index" type="file" name="option_images[]" accept="image/jpeg,image/png,image/gif,image/webp" x-bind:disabled="questionType !== 'mcq'" x-on:change="optionImageNames[index] = $event.target.files[0]?.name || ''"></div><template x-if="optionImages[index]"><span class="option-image-current"><img class="question-image-preview" x-bind:src="optionImages[index]" alt="Current answer image"><label class="image-remove"><input type="checkbox" x-bind:name="'remove_option_images[' + index + ']'" value="1" x-bind:disabled="questionType !== 'mcq'"> Remove image</label></span></template></div><input type="radio" name="correct_option" x-model.number="correctOption" x-bind:value="index" x-bind:disabled="questionType !== 'mcq'"><span>Correct</span><button class="btn secondary small" type="button" x-on:click="removeOption(index)" x-show="options.length > 2">Remove</button></div></template><button class="btn secondary small wizard-add" type="button" x-on:click="addOption()" x-show="options.length < 4">Add option</button></div>
            </section>
        </div>
    </div>
    <div class="wizard-actions"><button class="btn secondary" type="button" x-show="step > 1" x-on:click="step--" x-cloak>Previous</button><button class="btn secondary" type="button" x-show="step < 3" x-on:click="step++" x-cloak>Next</button><div class="wizard-nav"><button class="btn primary" type="submit">{{ $isEditing ? 'Save' : 'Create' }}</button><button class="btn secondary" type="submit" name="create_another" value="1" x-show="!{{ $isEditing ? 'true' : 'false' }}">{{ $isEditing ? 'Save' : 'Create' }} &amp; create another</button><a class="btn secondary" href="{{ $cancelUrl }}">Cancel</a></div></div>
</div>
<script>
    window.questionWizard = function (initial) { return { ...initial, step: 1, addOption() { if (this.options.length < 4) { this.options.push(''); this.optionImages.push(null); } }, removeOption(index) { if (this.options.length > 2) { this.options.splice(index, 1); this.optionImages.splice(index, 1); if (this.correctOption >= this.options.length) this.correctOption = this.options.length - 1; } }, insertMarker(field, marker) { const input = this.$refs[field]; const start = input.selectionStart; const end = input.selectionEnd; const value = this[field] || ''; const token = marker === 'Bold' ? '**' : marker === 'Italic' ? '_' : marker === 'Underline' ? '__' : ''; if (!token) return; this[field] = value.slice(0, start) + token + value.slice(start, end) + token + value.slice(end); this.$nextTick(() => { input.focus(); input.setSelectionRange(start + token.length, end + token.length); }); } }; };
</script>
<style media="not all">
    .question-creation-page{background:transparent;color:var(--admin-ink);padding:0;min-height:0}.question-creation-page .page-head h1{color:var(--admin-navy)}.question-breadcrumb{color:var(--admin-muted)}.question-breadcrumb a{color:var(--admin-blue)}.question-breadcrumb span{color:var(--admin-muted)}
    .question-wizard{background:var(--admin-white);color:var(--admin-ink);border:1px solid var(--admin-line);border-radius:8px;padding:0;box-shadow:0 2px 8px rgba(20,54,78,.04)}.question-wizard .wizard-panel{border:0;border-radius:0}.wizard-tabs{background:#f7fafb;border:1px solid var(--admin-line);border-radius:7px;margin:12px;padding:4px}.wizard-tab{color:var(--admin-muted);padding:11px 15px}.wizard-tab.active{background:#e8f2f8;color:var(--admin-blue)}.wizard-tab:hover{color:var(--admin-navy);background:#edf3f6}.wizard-body{padding:28px 24px}.question-wizard label{color:var(--admin-ink)}.question-wizard label small{color:var(--admin-muted)}.question-wizard input,.question-wizard select,.question-wizard textarea{background:#fff;border:1px solid #b9c7d2;color:var(--admin-ink);border-radius:5px}.question-wizard input:focus,.question-wizard select:focus,.question-wizard textarea:focus{outline:2px solid rgba(28,107,155,.25);border-color:var(--admin-blue)}.wizard-editor{border:1px solid #b9c7d2;background:#fff}.wizard-toolbar{border-bottom:1px solid var(--admin-line)}.wizard-toolbar button{color:var(--admin-ink)}.wizard-toolbar button:hover{background:#edf3f6}.wizard-editor textarea{background:#fff}.wizard-readonly{background:#f7fafb;border:1px solid var(--admin-line);color:var(--admin-ink);border-radius:5px}.wizard-switch input{background:#b9c7d2}.wizard-switch input:checked{background:var(--admin-blue)}.wizard-helper,.question-wizard .muted{color:var(--admin-muted)}.wizard-actions{padding:0 24px 24px}.question-wizard .btn.primary{background:var(--admin-blue);border-color:var(--admin-blue)}.question-wizard .btn.primary:hover{background:#145779}.question-wizard .btn.secondary{background:#fff;color:var(--admin-blue);border-color:var(--admin-blue)}
    .image-field{margin-top:14px}.question-image-preview{display:block;max-width:220px;max-height:140px;margin-top:10px;border:1px solid var(--admin-line);border-radius:5px;object-fit:contain;background:#f7fafb}.image-remove{display:flex;align-items:center;gap:6px;margin-top:8px;font-weight:400}.wizard-choice{display:flex;align-items:flex-start;gap:10px;margin:10px 0}.option-content{flex:1}.option-content .choice-text{width:100%;margin-bottom:6px}.option-image-current{display:block}.option-image-current .image-remove{font-size:12px}
</style>
