@php
    $cancelUrl = $cancelUrl ?? route('admin.courses.questions.index', $course);
    $selectedType = old('type', $question->type?->value ?? 'true_false');
    $selectedDifficulty = old('difficulty', $question->difficulty?->value ?? 'medium');
    $options = old('options', $question->options?->pluck('option_text')->all() ?: ['', '']);
    $selectedCorrect = old('correct_option', $question->options?->search(fn ($option) => $option->is_correct));
    $selectedAnswer = old('correct_answer', $question->type?->value === 'true_false' ? ($question->correct_answer_boolean ? 'true' : 'false') : $question->correct_answer_text);
@endphp
<div class="form-grid"><div class="field full"><label for="question_text">Question text</label><textarea id="question_text" name="question_text" required>{{ old('question_text', $question->question_text) }}</textarea></div><div class="field"><label for="question_type">Type</label><select id="question_type" name="type" required>@foreach($types as $item)<option value="{{ $item->value }}" @selected($selectedType === $item->value)>{{ $item->label() }}</option>@endforeach</select></div><div class="field"><label for="question_difficulty">Difficulty</label><select id="question_difficulty" name="difficulty" required>@foreach($difficulties as $item)<option value="{{ $item->value }}" @selected($selectedDifficulty === $item->value)>{{ $item->label() }}</option>@endforeach</select></div>
<div class="field full question-answer" data-answer="true_false"><label for="true_false_answer">Correct answer</label><select id="true_false_answer" name="correct_answer"><option value="true" @selected($selectedAnswer === 'true')>True</option><option value="false" @selected($selectedAnswer === 'false')>False</option></select></div>
<div class="field full question-answer" data-answer="input"><label for="input_answer">Correct answer</label><input id="input_answer" name="correct_answer" value="{{ $selectedAnswer }}" placeholder="Expected text answer"></div>
<div class="field full question-answer" data-answer="mcq"><label>Options <small class="muted">Choose the correct option.</small></label><div id="questionOptions">@foreach($options as $index => $option)<div class="question-option"><input name="options[]" value="{{ $option }}" placeholder="Option {{ chr(65 + $index) }}"><label><input type="radio" name="correct_option" value="{{ $index }}" @checked((string) $selectedCorrect === (string) $index)> Correct</label><button type="button" class="btn secondary small remove-option">Remove</button></div>@endforeach</div><button type="button" class="btn secondary small" id="addQuestionOption">Add option</button></div></div><div class="actions" style="margin-top:20px"><button class="btn">Save question</button><a class="btn secondary" href="{{ $cancelUrl }}">Cancel</a></div>
<script>
(() => { const type = document.getElementById('question_type'), blocks = [...document.querySelectorAll('.question-answer')], options = document.getElementById('questionOptions');
const sync = () => blocks.forEach(block => { const active = block.dataset.answer === type.value; block.hidden = !active; block.querySelectorAll('input,select').forEach(input => { input.disabled = !active; input.required = active && (input.name === 'correct_answer' || input.name === 'options[]'); }); });
type.addEventListener('change', sync); sync();
document.getElementById('addQuestionOption').addEventListener('click', () => { const count = options.children.length; if (count >= 4) return; const row = document.createElement('div'); row.className = 'question-option'; row.innerHTML = '<input name="options[]" placeholder="Option ' + String.fromCharCode(65 + count) + '"><label><input type="radio" name="correct_option" value="' + count + '"> Correct</label><button type="button" class="btn secondary small remove-option">Remove</button>'; options.appendChild(row); sync(); });
options.addEventListener('click', event => { if (!event.target.classList.contains('remove-option') || options.children.length <= 2) return; event.target.closest('.question-option').remove(); [...options.children].forEach((row, index) => { row.querySelector('input[name="correct_option"]').value = index; row.querySelector('input[name="options[]"]').placeholder = 'Option ' + String.fromCharCode(65 + index); }); });
})();
</script>
<style>.question-option{display:flex;align-items:center;gap:10px;margin:8px 0}.question-option>input{flex:1}.question-option label{font-weight:400;white-space:nowrap}</style>
