@extends('layouts.admin')
@section('admin-content')
<style>[x-cloak]{display:none!important}.admin-table-loading{opacity:.55;pointer-events:none}.admin-sort{border:0;background:transparent;color:inherit;font:inherit;font-weight:600;cursor:pointer;padding:0}.admin-sort:hover{color:var(--admin-blue)}.admin-sort-icon{font-size:11px;margin-left:3px}.admin-table-error{background:#fef3f2;color:#b42318;border-radius:5px;padding:10px 12px;margin-bottom:15px}.subject-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.subject-status-toggle{cursor:pointer!important;pointer-events:auto!important;touch-action:manipulation}.subject-row-error{display:block;color:#b42318;font-size:12px;margin-top:5px}</style>
<div class="page-head"><div><h1>Subjects</h1><p>Search, filter, and sort Subjects without leaving this page.</p></div><a class="btn" href="{{ route('admin.courses.create') }}">Create Subject</a></div>
<div class="card" x-data="subjectTable(@js(route('admin.subjects.data')), @js($initialCourses), @js($initialMeta), @js($sort), @js($direction))">
    <form class="search" x-on:submit.prevent="load(1, true)"><input x-model="search" x-on:input.debounce.350ms="load(1)" placeholder="Search code or name" autocomplete="off"><select x-model="status" x-on:change="load(1)"><option value="">All Statuses</option><option value="active">Active</option><option value="retired">Archived</option></select><button class="btn secondary" type="submit">Apply</button><button class="btn secondary" type="button" x-show="hasFilters()" x-on:click="clearFilters()" x-cloak>Clear</button></form>
    <div class="admin-table-error" x-show="error" x-text="error" x-cloak></div>
    <div class="table-wrap" x-bind:class="loading ? 'admin-table-loading' : ''"><table class="table"><thead><tr><th><button class="admin-sort" type="button" x-on:click="sortBy('code')">Code <span class="admin-sort-icon" x-text="sortIcon('code')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('name')">Subject <span class="admin-sort-icon" x-text="sortIcon('name')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('level')">Level <span class="admin-sort-icon" x-text="sortIcon('level')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('status')">Status <span class="admin-sort-icon" x-text="sortIcon('status')"></span></button></th><th>Actions</th></tr></thead><tbody><template x-for="subject in rows" :key="subject.id"><tr><td x-text="subject.code"></td><td x-text="subject.name"></td><td x-text="subject.level"></td><td><div class="admin-status-cell"><span class="badge" x-bind:class="subject.archived ? 'archived' : subject.status" x-text="subject.archived ? 'Archived' : subject.status_label"></span></div></td><td><div class="admin-actions-cell"><a x-bind:href="subject.view_url">View</a><template x-if="subject.can_archive"><button class="btn secondary small subject-status-toggle" type="button" x-on:click.prevent="archiveSubject(subject)" x-bind:disabled="subject.archiving" x-bind:aria-busy="subject.archiving ? 'true' : 'false'" x-text="subject.archiving ? 'Updating...' : 'Archive'"></button></template><template x-if="subject.can_unarchive"><button class="btn secondary small subject-status-toggle" type="button" x-on:click.prevent="unarchiveSubject(subject)" x-bind:disabled="subject.archiving" x-bind:aria-busy="subject.archiving ? 'true' : 'false'" x-text="subject.archiving ? 'Updating...' : 'Unarchive'"></button></template><span class="subject-row-error" x-show="subject.rowError" x-text="subject.rowError" x-cloak></span></div></td></tr></template><tr x-show="!loading && rows.length === 0" x-cloak><td colspan="5"><div class="admin-empty-row"><span class="admin-empty-row-icon">ðŸ”</span>No Subjects found.</div></td></tr></tbody></table></div>
    <div class="actions" style="justify-content:space-between;margin-top:18px"><span class="muted" x-text="meta.total ? 'Showing '+meta.from+' to '+meta.to+' of '+meta.total+' Subjects' : 'No Subjects found'"></span><div class="actions"><button class="btn secondary" type="button" x-on:click="load(meta.current_page - 1, true)" x-bind:disabled="loading || meta.current_page <= 1">Previous</button><span class="muted" x-text="meta.current_page+' / '+meta.last_page"></span><button class="btn secondary" type="button" x-on:click="load(meta.current_page + 1, true)" x-bind:disabled="loading || meta.current_page >= meta.last_page">Next</button></div></div>
</div>
<script>
    window.subjectTable = function (endpoint, initialRows, initialMeta, initialSort, initialDirection) {
        return { endpoint, rows: (initialRows || []).map(subject => ({ ...subject, archiving: false, rowError: '' })), meta: initialMeta || { current_page: 1, last_page: 1, total: 0, from: null, to: null }, search: @js($search), status: @js($status), sort: initialSort || 'created_at', direction: initialDirection || 'desc', loading: false, error: '', request: null,
            init() { window.addEventListener('popstate', () => { const params = new URLSearchParams(window.location.search); this.search = params.get('search') || ''; this.status = params.get('status') || ''; this.sort = params.get('sort') || 'created_at'; this.direction = params.get('direction') === 'asc' ? 'asc' : 'desc'; this.load(Number(params.get('page') || 1), false); }); this.syncUrl(false); },
            syncUrl(push = false) { const url = new URL(window.location.href); const params = url.searchParams; this.search ? params.set('search', this.search) : params.delete('search'); this.status ? params.set('status', this.status) : params.delete('status'); this.sort !== 'created_at' ? params.set('sort', this.sort) : params.delete('sort'); this.direction !== 'desc' ? params.set('direction', this.direction) : params.delete('direction'); this.meta.current_page > 1 ? params.set('page', this.meta.current_page) : params.delete('page'); window.history[push ? 'pushState' : 'replaceState']({}, '', url); },
            hasFilters() { return this.search || this.status; }, clearFilters() { this.search = ''; this.status = ''; this.load(1, true); }, sortIcon(field) { return this.sort === field ? (this.direction === 'asc' ? 'â–²' : 'â–¼') : 'â†•'; }, sortBy(field) { if (this.sort === field) this.direction = this.direction === 'asc' ? 'desc' : 'asc'; else { this.sort = field; this.direction = 'asc'; } this.load(1, true); },
            async load(page, push = false) { page = Math.max(1, page || 1); if (this.request) this.request.abort(); this.request = new AbortController(); const params = new URLSearchParams({ page, sort: this.sort, direction: this.direction }); if (this.search) params.set('search', this.search); if (this.status) params.set('status', this.status); this.loading = true; this.error = ''; try { const response = await fetch(this.endpoint + '?' + params.toString(), { headers: { Accept: 'application/json' }, signal: this.request.signal }); if (!response.ok) throw new Error('Subject search failed'); const payload = await response.json(); this.rows = (payload.data || []).map(subject => ({ ...subject, archiving: false, rowError: '' })); this.meta = payload.meta; this.syncUrl(push); } catch (error) { if (error.name !== 'AbortError') this.error = 'Subjects could not be loaded. Try again.'; } finally { this.loading = false; } },
            async archiveSubject(subject) { if (!subject.can_archive || subject.archiving) return; await this.changeArchiveState(subject, subject.archive_url, 'Subject could not be archived.', 'archived'); },
            async unarchiveSubject(subject) { if (!subject.can_unarchive || subject.archiving) return; await this.changeArchiveState(subject, subject.unarchive_url, 'Subject could not be unarchived.', 'active'); },
            async changeArchiveState(subject, url, errorMessage, state) { subject.archiving = true; subject.rowError = ''; this.error = ''; try { const response = await fetch(url, { method: 'PATCH', credentials: 'same-origin', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content || '', 'X-Requested-With': 'XMLHttpRequest' }, body: '{}' }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || errorMessage); subject.status = payload.status || (state === 'active' ? 'active' : 'retired'); subject.status_label = payload.status_label || (state === 'active' ? 'Active' : 'Archived'); subject.archived = state === 'archived'; subject.can_archive = state === 'active'; subject.can_unarchive = state === 'archived'; } catch (exception) { subject.rowError = exception.message || errorMessage; this.error = subject.rowError; } finally { subject.archiving = false; } }
        };
    };
</script>
@endsection
