@extends('layouts.admin')
@section('admin-content')
<style>[x-cloak]{display:none!important}.admin-table-loading{opacity:.55;pointer-events:none}.admin-sort{border:0;background:transparent;color:inherit;font:inherit;font-weight:600;cursor:pointer;padding:0}.admin-sort:hover{color:var(--admin-blue)}.admin-sort-icon{font-size:11px;margin-left:3px}.admin-table-error{background:#fef3f2;color:#b42318;border-radius:5px;padding:10px 12px;margin-bottom:15px}</style>
<div class="page-head"><div><h1>Subjects</h1><p>Search, filter, and sort Subjects without leaving this page.</p></div><a class="btn" href="{{ route('admin.courses.create') }}">Create Subject</a></div>
<div class="card" x-data="subjectTable(@js(route('admin.subjects.data')), @js($initialCourses), @js($initialMeta))">
    <form class="search" x-on:submit.prevent="load(1)"><input x-model="search" x-on:input.debounce.350ms="load(1)" placeholder="Search code, name, or provider" autocomplete="off"><select x-model="status" x-on:change="load(1)"><option value="">All Statuses</option><option value="active">Active</option><option value="retired">Retired</option></select><button class="btn secondary" type="submit">Apply</button><button class="btn secondary" type="button" x-show="hasFilters()" x-on:click="clearFilters()" x-cloak>Clear</button></form>
    <div class="admin-table-error" x-show="error" x-text="error" x-cloak></div>
    <div class="table-wrap" x-bind:class="loading ? 'admin-table-loading' : ''"><table class="table"><thead><tr><th><button class="admin-sort" type="button" x-on:click="sortBy('code')">Code <span class="admin-sort-icon" x-text="sortIcon('code')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('name')">Subject <span class="admin-sort-icon" x-text="sortIcon('name')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('provider')">Provider <span class="admin-sort-icon" x-text="sortIcon('provider')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('level')">Level <span class="admin-sort-icon" x-text="sortIcon('level')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('status')">Status <span class="admin-sort-icon" x-text="sortIcon('status')"></span></button></th><th></th></tr></thead><tbody><template x-for="subject in rows" :key="subject.id"><tr><td x-text="subject.code"></td><td x-text="subject.name"></td><td x-text="subject.provider"></td><td x-text="subject.level"></td><td><span class="badge" x-bind:class="subject.status" x-text="subject.status_label"></span></td><td><a x-bind:href="subject.view_url">View</a></td></tr></template><tr x-show="!loading && rows.length === 0" x-cloak><td colspan="6" class="muted">No Subjects found.</td></tr></tbody></table></div>
    <div class="actions" style="justify-content:space-between;margin-top:18px"><span class="muted" x-text="meta.total ? 'Showing '+meta.from+' to '+meta.to+' of '+meta.total+' Subjects' : 'No Subjects found'"></span><div class="actions"><button class="btn secondary" type="button" x-on:click="load(meta.current_page - 1)" x-bind:disabled="loading || meta.current_page <= 1">Previous</button><span class="muted" x-text="meta.current_page+' / '+meta.last_page"></span><button class="btn secondary" type="button" x-on:click="load(meta.current_page + 1)" x-bind:disabled="loading || meta.current_page >= meta.last_page">Next</button></div></div>
</div>
<script>
    window.subjectTable = function (endpoint, initialRows, initialMeta) {
        return { endpoint, rows: initialRows || [], meta: initialMeta || { current_page: 1, last_page: 1, total: 0, from: null, to: null }, search: @js($search), status: @js($status), sort: 'created_at', direction: 'desc', loading: false, error: '', request: null,
            hasFilters() { return this.search || this.status; }, clearFilters() { this.search = ''; this.status = ''; this.load(1); }, sortIcon(field) { return this.sort === field ? (this.direction === 'asc' ? '▲' : '▼') : '↕'; }, sortBy(field) { if (this.sort === field) this.direction = this.direction === 'asc' ? 'desc' : 'asc'; else { this.sort = field; this.direction = 'asc'; } this.load(1); },
            async load(page) { page = Math.max(1, page || 1); if (this.request) this.request.abort(); this.request = new AbortController(); const params = new URLSearchParams({ page, sort: this.sort, direction: this.direction }); if (this.search) params.set('search', this.search); if (this.status) params.set('status', this.status); this.loading = true; this.error = ''; try { const response = await fetch(this.endpoint + '?' + params.toString(), { headers: { Accept: 'application/json' }, signal: this.request.signal }); if (!response.ok) throw new Error('Subject search failed'); const payload = await response.json(); this.rows = payload.data; this.meta = payload.meta; } catch (error) { if (error.name !== 'AbortError') this.error = 'Subjects could not be loaded. Try again.'; } finally { this.loading = false; } }
        };
    };
</script>
@endsection
