@extends('layouts.admin')
@section('admin-content')
<style>[x-cloak]{display:none!important}.admin-table-loading{opacity:.55;pointer-events:none}.admin-sort{border:0;background:transparent;color:inherit;font:inherit;font-weight:600;cursor:pointer;padding:0}.admin-sort:hover{color:var(--admin-blue)}.admin-sort-icon{font-size:11px;margin-left:3px}.admin-table-error{background:#fef3f2;color:#b42318;border-radius:5px;padding:10px 12px;margin-bottom:15px}</style>
<div class="page-head"><div><h1>Classes</h1><p>Search, filter, and sort Exams without leaving this page.</p></div><a class="btn" href="{{ route('admin.classes.create') }}">Create class</a></div>
<div class="card" x-data="classTable(@js(route('admin.classes.data')), @js($initialClasses), @js($initialMeta))">
    <form class="search" x-on:submit.prevent="load(1)"><input x-model="search" x-on:input.debounce.350ms="load(1)" placeholder="Search class number or Subject" autocomplete="off"><select x-model="courseId" x-on:change="load(1)"><option value="">All Subjects</option>@foreach($courses as $course)<option value="{{ $course->id }}">{{ $course->name }}</option>@endforeach</select><select x-model="providerId" x-on:change="load(1)"><option value="">All Providers</option>@foreach($providers as $provider)<option value="{{ $provider->id }}">{{ $provider->name }}</option>@endforeach</select><select x-model="status" x-on:change="load(1)"><option value="">All Statuses</option><option value="planned">Planned</option><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button class="btn secondary" type="submit">Apply</button><button class="btn secondary" type="button" x-show="hasFilters()" x-on:click="clearFilters()" x-cloak>Clear</button></form>
    <div class="admin-table-error" x-show="error" x-text="error" x-cloak></div>
    <div class="table-wrap" x-bind:class="loading ? 'admin-table-loading' : ''"><table class="table"><thead><tr><th><button class="admin-sort" type="button" x-on:click="sortBy('class_number')">Class number <span class="admin-sort-icon" x-text="sortIcon('class_number')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('course')">Subject <span class="admin-sort-icon" x-text="sortIcon('course')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('provider')">Provider <span class="admin-sort-icon" x-text="sortIcon('provider')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('starts_at')">Schedule <span class="admin-sort-icon" x-text="sortIcon('starts_at')"></span></button></th><th><button class="admin-sort" type="button" x-on:click="sortBy('status')">Status <span class="admin-sort-icon" x-text="sortIcon('status')"></span></button></th><th></th></tr></thead><tbody><template x-for="trainingClass in rows" :key="trainingClass.id"><tr><td x-text="trainingClass.class_number"></td><td x-text="trainingClass.course"></td><td x-text="trainingClass.provider"></td><td><span x-text="trainingClass.starts_at"></span><template x-if="trainingClass.ends_at !== '—'"><br><small class="muted" x-text="'Ends '+trainingClass.ends_at"></small></template></td><td><span class="badge" x-bind:class="trainingClass.status" x-text="trainingClass.status_label"></span></td><td><a x-bind:href="trainingClass.view_url">View</a></td></tr></template><tr x-show="!loading && rows.length === 0" x-cloak><td colspan="6" class="muted">No classes found.</td></tr></tbody></table></div>
    <div class="actions" style="justify-content:space-between;margin-top:18px"><span class="muted" x-text="meta.total ? 'Showing '+meta.from+' to '+meta.to+' of '+meta.total+' classes' : 'No classes found'"></span><div class="actions"><button class="btn secondary" type="button" x-on:click="load(meta.current_page - 1)" x-bind:disabled="loading || meta.current_page <= 1">Previous</button><span class="muted" x-text="meta.current_page+' / '+meta.last_page"></span><button class="btn secondary" type="button" x-on:click="load(meta.current_page + 1)" x-bind:disabled="loading || meta.current_page >= meta.last_page">Next</button></div></div>
</div>
<script>
    window.classTable = function (endpoint, initialRows, initialMeta) {
        return { endpoint, rows: initialRows || [], meta: initialMeta || { current_page: 1, last_page: 1, total: 0, from: null, to: null }, search: @js($search), courseId: @js((string) $courseId), providerId: @js((string) $providerId), status: @js($status), sort: 'created_at', direction: 'desc', loading: false, error: '', request: null,
            hasFilters() { return this.search || this.courseId || this.providerId || this.status; }, clearFilters() { this.search = ''; this.courseId = ''; this.providerId = ''; this.status = ''; this.load(1); }, sortIcon(field) { return this.sort === field ? (this.direction === 'asc' ? '▲' : '▼') : '↕'; }, sortBy(field) { if (this.sort === field) this.direction = this.direction === 'asc' ? 'desc' : 'asc'; else { this.sort = field; this.direction = 'asc'; } this.load(1); },
            async load(page) { page = Math.max(1, page || 1); if (this.request) this.request.abort(); this.request = new AbortController(); const params = new URLSearchParams({ page, sort: this.sort, direction: this.direction }); if (this.search) params.set('search', this.search); if (this.courseId) params.set('course_id', this.courseId); if (this.providerId) params.set('provider_id', this.providerId); if (this.status) params.set('status', this.status); this.loading = true; this.error = ''; try { const response = await fetch(this.endpoint + '?' + params.toString(), { headers: { Accept: 'application/json' }, signal: this.request.signal }); if (!response.ok) throw new Error('Class search failed'); const payload = await response.json(); this.rows = payload.data; this.meta = payload.meta; } catch (error) { if (error.name !== 'AbortError') this.error = 'Classes could not be loaded. Try again.'; } finally { this.loading = false; } }
        };
    };
</script>
@endsection
