<?php

namespace App\Http\Requests\Admin;

use App\Enums\Gender;
use App\Models\Role;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreUserRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->isAdmin() === true;
    }

    protected function prepareForValidation(): void
    {
        if (filled($this->wellsharp_id)) {
            $this->merge(['wellsharp_id' => strtoupper(trim((string) $this->wellsharp_id))]);
        }
    }

    public function rules(): array
    {
        return [
            // Left blank, WellSharp ID and Password are auto-generated by
            // CreateUserAction from the submitted name (and, for the
            // password, WellSharp's security policy below). Admin may still
            // supply either explicitly, so uniqueness/strength are still
            // validated when present.
            'wellsharp_id' => ['nullable', 'string', 'max:64', 'alpha_dash', 'unique:users,wellsharp_id'],
            'first_name' => ['required', 'string', 'max:100'],
            'last_name' => ['required', 'string', 'max:100'],
            'email' => ['nullable', 'email', 'max:255', 'unique:users,email'],
            'phone' => ['nullable', 'string', 'max:32'],
            // Age is derived from birthday (see UserProfile::calculateAge()),
            // never accepted as its own input, so the bounds that used to
            // live on 'age' (1-120) are enforced here instead.
            'birthday' => ['nullable', 'date', 'before:today', 'after:'.now()->subYears(120)->toDateString()],
            'address' => ['nullable', 'string', 'max:255'],
            'country' => ['nullable', 'string', 'max:100'],
            'state' => ['nullable', 'string', 'max:100'],
            'city' => ['nullable', 'string', 'max:100'],
            'postal_code' => ['nullable', 'string', 'max:32'],
            'company' => ['nullable', 'string', 'max:180'],
            'position' => ['nullable', 'string', 'max:180'],
            'company_contact' => ['nullable', 'string', 'max:100'],
            'employee_id' => ['nullable', 'string', 'max:64'],
            'gender' => ['nullable', Rule::enum(Gender::class)],
            'password' => ['nullable', 'string', 'confirmed', ...Role::passwordLengthRules($this->targetRoleKey())],
            'role_id' => [Rule::requiredIf(fn (): bool => ! $this->routeIs('admin.students.store')), Rule::exists('roles', 'id')],
            'group_ids' => ['nullable', 'array'],
            'group_ids.*' => ['integer', Rule::exists('student_groups', 'id')],
        ];
    }

    /**
     * The role a Student-only route is always creating for is not a
     * client-controllable value (the admin.students.store route forces it
     * server-side in StudentController, after validation) - the
     * routeIs() check here mirrors that, rather than trusting role_id, which
     * is only meaningful on the general admin.users.store route.
     */
    private function targetRoleKey(): ?string
    {
        if ($this->routeIs('admin.students.store')) {
            return Role::STUDENT;
        }

        return Role::query()->find($this->input('role_id'))?->key;
    }
}
